### PR TITLE
Upgrade prometheus-operator crds

### PR DESCRIPTION
**Pull request by QuentinBisson**

### CODE REVIEW

**Review by mcbenjemaa — APPROVED** [review]
LGTM

**Comment by QuentinBisson** [comment]
I did not test it yet. I'm waiting for https://github.com/giantswarm/prometheus-operator-app/pull/195 to be ready first

**Comment by QuentinBisson** [comment]
@TheoBrigitte I'm not really sure what you want me to describe in the changelog here as this is due to the updte in the prometheus operator crd themselves

**Comment by QuentinBisson** [comment]
It's deploying successfully on Gauss

**Comment by TheoBrigitte** [comment]
> @TheoBrigitte I'm not really sure what you want me to describe in the changelog here as this is due to the updte in the prometheus operator crd themselves

I looks like a minor update but I think its worth going through the changes in the upstream repo changelog and find if there's anything breaking or we should be aware of, if yes please add this into our changelog. Otherwise move on.

**Comment by TheoBrigitte** [comment]
Can we close this in favor of https://github.com/giantswarm/prometheus-operator-crd/pull/36 ?

**Comment by QuentinBisson** [comment]
Definitely

**Pull request closed without merging**
